[build]
  publish = "out"
  command = "npm run build && npm run export"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/favicon.ico"
  to = "/profile-pic.jpeg"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
